###
// Upload avatar.
POST http://localhost:8080/avatar?studentId=2
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="weasley_ron"; filename="weasley_ron.jpg"
Content-Type: image/jpeg

< ./uploads/weasley_ron.jpg
--WebAppBoundary

###
// Get avatar from DB.
GET http://localhost:8080/avatar/db?studentId=2

###
// Get avatar from file system.
GET http://localhost:8080/avatar/fs?studentId=2

###
// Get all - hw 4.1 https://my.sky.pro/student-cabinet/stream-lesson/34696/homework
GET http://localhost:8080/avatar?page=1&size=1